name: fitforge
description: "FitForge — Gamified Fitness & Nutrition App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  dio: ^5.4.0
  flutter_secure_storage: ^10.3.1
  url_launcher: ^6.3.2
  app_links: ^7.0.0
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  file_picker: ^8.1.6
  excel: ^4.0.6
  csv: ^6.0.0
  socket_io_client: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
